//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int Id { get; set; }
        public Nullable<int> FK_Users_Id { get; set; }
        public Nullable<int> FK_Notifier_Users_Id { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string Message { get; set; }
        public string GotoLink { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
