//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public int FK_Users_Id { get; set; }
        public string Contact { get; set; }
        public string Email { get; set; }
        public string ProfileImage { get; set; }
        public string Address { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Religion { get; set; }
        public string Relationship { get; set; }
    
        public virtual User User { get; set; }
    }
}
